version: "3"

services:
  calculation:
    container_name: calculation_backend
    build: .
    ports:
      - "3030:3030"
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      - MONGO_CONNECTION=mongodb://mongodb:27017/calculation
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="calculation"